Change method to alter Dockerfile and add debug output

diff --git a/.github/workflows/container-image-build-validation.yaml b/.github/workflows/container-image-build-validation.yaml
--- a/.github/workflows/container-image-build-validation.yaml
+++ b/.github/workflows/container-image-build-validation.yaml
@@ -47,8 +47,18 @@ jobs:
         uses: actions/checkout@v3
       - name: Enhance Dockerfile with test.json
         run: |
-          echo "" >> Dockerfile
-          echo "COPY /examples/test.json /test.json"
+          if [ ! -f "./Dockerfile" ]; then
+            echo "ERROR: File not found exception for Dockerfile" >&2
+            exit 1
+          fi
+          echo "====================[Original]=========================="
+          cat Dockerfile
+          echo "========================================================"
+          sed '/EXPOSE 5020\/tcp/i COPY /examples/test.json /test.json' ./Dockerfile || exit 1
+          echo "====================[Modified]=========================="
+          cat Dockerfile
+          echo "========================================================"
+
       - name: Log in to Github container registry
         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
       - name: Build container for functionality test
