Try to add functionality test (#29)
* Try to add functionality test

* Fixing services ports section

* Try to use local image from previous job

* Disable function test execution

* Try to fix error

* Another test

* Fix artifact upload

* Fix artifact download

* Extract image ID

* Fix Typo

* Docker images debug output

* Add more debug output

* Add terst.json inside container by default

* Add quotes to options

* Remove option

* Change server name

* Add feature to set configuration file via environment variable

* Remove job dependency

* Remove platform support in functionality test build

* Replace double with single quotes

* Add conection test

* Change method to alter Dockerfile and add debug output

* Use an alternate Dockerfile that implements a test.json

* Fix yaml syntax

* Remove CMD, beacuse the functionality changed

* Add output validation

* Add folding details

* Try fix folding

* Try fix folding

* Another try for folding content

* Testing folding

diff --git a/.github/workflows/container-image-build-validation.yaml b/.github/workflows/container-image-build-validation.yaml
--- a/.github/workflows/container-image-build-validation.yaml
+++ b/.github/workflows/container-image-build-validation.yaml
@@ -38,6 +38,156 @@ jobs:
         with:
           name: container-build
           path: /tmp/container.tar
+
+  function-test-preparation:
+    name: Container functionality test preparation
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout GIT repository
+        uses: actions/checkout@v3
+      - name: Log in to Github container registry
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+      - name: Build container for functionality test
+        uses: docker/build-push-action@v4.1.0
+        with:
+          push: true
+          load: false
+          context: .
+          file: ./Dockerfile.test
+          tags: ghcr.io/cybcon/modbus-server/modbus-server:test
+
+  function-test-execution:
+    name: Container functionality test execution
+    needs: function-test-preparation
+    runs-on: ubuntu-latest
+    services:
+      modbusserver:
+        image: ghcr.io/cybcon/modbus-server/modbus-server:test
+        env:
+          CONFIG_FILE: /test.json
+        ports:
+          - 5020:5020
+    steps:
+      - name: Pull Modbus Client for functionality test
+        run: |
+          docker pull oitc/modbus-client:latest
+          echo "# Modbus functionality test" >> ${GITHUB_STEP_SUMMARY}
+      - name: Get modbus server address
+        id: modbus-server-address
+        run: |
+          LOCAL_MACHINE=$(ifconfig -a eth0|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:")
+          echo "DEBUG: ${LOCAL_MACHINE}"
+          echo "ip=${LOCAL_MACHINE}" >> $GITHUB_OUTPUT
+      - name: Validate server endpoint
+        run: |
+          modbusserver=${{steps. modbus-server-address.outputs.ip}}
+          ping -c 1 -q ${modbusserver}
+          RC=$?
+          if [ ${RC} -gt 0 ]; then
+            echo "ERROR: Modbus slave not reachable" >&2
+            exit 1
+          fi
+      - name: Test Discrete Output Coils
+        run: |
+          modbusserver=${{steps. modbus-server-address.outputs.ip}}
+          echo "## Get Discrete Output Coils" >> ${GITHUB_STEP_SUMMARY}
+          echo '<details>' >> ${GITHUB_STEP_SUMMARY}
+          echo '  <summary>Test output details</summary>' >> ${GITHUB_STEP_SUMMARY}
+          echo "" >> ${GITHUB_STEP_SUMMARY}
+          echo '  ```' >> ${GITHUB_STEP_SUMMARY}
+          echo "  docker run --rm oitc/modbus-client:latest -s ${modbusserver} -p 5020 -t 1 -r 0 -l 10" >> ${GITHUB_STEP_SUMMARY}
+          docker run --rm oitc/modbus-client:latest -s ${modbusserver} -p 5020 -t 1 -r 0 -l 10 > output.tmp 2>&1
+          cat output.tmp | while read line
+          do
+            echo "  ${line}" >> ${GITHUB_STEP_SUMMARY}
+          done
+          echo '  ```' >> ${GITHUB_STEP_SUMMARY}
+          echo '</details>' >> ${GITHUB_STEP_SUMMARY}
+          echo "" >> ${GITHUB_STEP_SUMMARY}
+          # analyze output
+          RESULT=$(cat output.tmp | grep ^2 | awk '{print $3}')
+          if [ "${RESULT}" == "True" ]; then
+            echo "Test succesfull :white_check_mark:" >> ${GITHUB_STEP_SUMMARY}
+          else
+            echo "Test failed :x:" >> ${GITHUB_STEP_SUMMARY}
+            exit 1
+          fi
+      - name: Test Discrete Input Contacts
+        run: |
+          modbusserver=${{steps. modbus-server-address.outputs.ip}}
+          echo "## Get Discrete Input Contacts" >> ${GITHUB_STEP_SUMMARY}
+          echo '<details>' >> ${GITHUB_STEP_SUMMARY}
+          echo '  <summary>Test output details</summary>' >> ${GITHUB_STEP_SUMMARY}
+          echo "" >> ${GITHUB_STEP_SUMMARY}
+          echo '  ```' >> ${GITHUB_STEP_SUMMARY}
+          echo "  docker run --rm oitc/modbus-client:latest -s ${modbusserver} -p 5020 -t 2 -r 0 -l 10" >> ${GITHUB_STEP_SUMMARY}
+          docker run --rm oitc/modbus-client:latest -s ${modbusserver} -p 5020 -t 2 -r 0 -l 10 > output.tmp 2>&1
+          cat output.tmp | while read line
+          do
+            echo "  ${line}" >> ${GITHUB_STEP_SUMMARY}
+          done
+          echo '  ```' >> ${GITHUB_STEP_SUMMARY}
+          echo '</details>' >> ${GITHUB_STEP_SUMMARY}
+          echo "" >> ${GITHUB_STEP_SUMMARY}
+          # analyze output
+          RESULT=$(cat output.tmp | grep ^10002 | awk '{print $3}')
+          if [ "${RESULT}" == "True" ]; then
+            echo "Test succesfull :white_check_mark:" >> ${GITHUB_STEP_SUMMARY}
+          else
+            echo "Test failed :x:" >> ${GITHUB_STEP_SUMMARY}
+            exit 1
+          fi
+      - name: Test Analog Output Holding Register
+        run: |
+          modbusserver=${{steps. modbus-server-address.outputs.ip}}
+          echo "## Get Analog Output Holding Register" >> ${GITHUB_STEP_SUMMARY}
+          echo '<details>' >> ${GITHUB_STEP_SUMMARY}
+          echo '  <summary>Test output details</summary>' >> ${GITHUB_STEP_SUMMARY}
+          echo "" >> ${GITHUB_STEP_SUMMARY}
+          echo '  ```' >> ${GITHUB_STEP_SUMMARY}
+          echo "  docker run --rm oitc/modbus-client:latest -s ${modbusserver} -p 5020 -t 3 -r 0 -l 10" >> ${GITHUB_STEP_SUMMARY}
+          docker run --rm oitc/modbus-client:latest -s ${modbusserver} -p 5020 -t 3 -r 0 -l 10 > output.tmp 2>&1
+          cat output.tmp | while read line
+          do
+            echo "  ${line}" >> ${GITHUB_STEP_SUMMARY}
+          done
+          echo '  ```' >> ${GITHUB_STEP_SUMMARY}
+          echo '</details>' >> ${GITHUB_STEP_SUMMARY}
+          echo "" >> ${GITHUB_STEP_SUMMARY}
+          # analyze output
+          RESULT=$(cat output.tmp | grep ^40002 | awk '{print $2}')
+          if [ "${RESULT}" == "0xCC03" ]; then
+            echo "Test succesfull :white_check_mark:" >> ${GITHUB_STEP_SUMMARY}
+          else
+            echo "Test failed :x:" >> ${GITHUB_STEP_SUMMARY}
+            exit 1
+          fi
+      - name: Test Analog Input Register
+        run: |
+          modbusserver=${{steps. modbus-server-address.outputs.ip}}
+          echo "## Get Analog Input Register" >> ${GITHUB_STEP_SUMMARY}
+          echo '<details>' >> ${GITHUB_STEP_SUMMARY}
+          echo '  <summary>Test output details</summary>' >> ${GITHUB_STEP_SUMMARY}
+          echo "" >> ${GITHUB_STEP_SUMMARY}
+          echo '  ```' >> ${GITHUB_STEP_SUMMARY}
+          echo "  docker run --rm oitc/modbus-client:latest -s ${modbusserver} -p 5020 -t 4 -r 0 -l 10" >> ${GITHUB_STEP_SUMMARY}
+          docker run --rm oitc/modbus-client:latest -s ${modbusserver} -p 5020 -t 4 -r 0 -l 10 > output.tmp 2>&1
+          cat output.tmp | while read line
+          do
+            echo "  ${line}" >> ${GITHUB_STEP_SUMMARY}
+          done
+          echo '  ```' >> ${GITHUB_STEP_SUMMARY}
+          echo '</details>' >> ${GITHUB_STEP_SUMMARY}
+          echo "" >> ${GITHUB_STEP_SUMMARY}
+          # analyze output
+          RESULT=$(cat output.tmp | grep ^30002 | head -1 | awk '{print $2}')
+          if [ "${RESULT}" == "0xDD03" ]; then
+            echo "Test succesfull :white_check_mark:" >> ${GITHUB_STEP_SUMMARY}
+          else
+            echo "Test failed :x:" >> ${GITHUB_STEP_SUMMARY}
+            exit 1
+          fi
+
   scan:
     name: Container vulnerability scan
     needs: container-build
